### ISSUE TITLE
Fix sh.st

### ISSUE THREAD

**Issue by thangngoc89** [matteocontrini/node-bypasser#1]
Hey @matteocontrini 

This project is exactly what I need right now. I have a bunch of sh.st links and I want to unshorten them. But It seems like sh.st support is broken. Could you please fix it?

**Comment by matteocontrini** [comment]
I'll take a look :)

**Comment by matteocontrini** [comment]
Easier than expected... but I can't believe it's that easy.
c377f0245442817549e93492b450ac15680a24e1

v1.0.4 is out on npm.
Let me know.

**Comment by thangngoc89** [comment]
@matteocontrini accutally, I fixed it myself. But thanks anyway. 

Do you interesting in add more sites into this repo ?

I can help.

**Comment by matteocontrini** [comment]
Yes I accept more sites but before that I'd like to change the structure of the module so that every service has a file. I'll see if I can do that today.

**Comment by thangngoc89** [comment]
Yeah. Please refactor it :)

**Comment by matteocontrini** [comment]
@thangngoc89 it should be better now. To add a service, create a new file in the `services` directory. Copy the code from an existing service (sh.st for example), so you have a schema of how it works.

https://github.com/matteocontrini/node-bypasser/commit/27e8413afdb871c179d1785791991b331596cd14
