### ISSUE TITLE
Nested/chain short link bypass

### ISSUE THREAD

**Issue by thangngoc89** [matteocontrini/node-bypasser#15]
Some service like linkbucks.com provided a tons of domains for their users.
![image](https://cloud.githubusercontent.com/assets/3049054/11074905/da133512-8824-11e5-9fbd-cb7bb7d1661b.png)
But all of them only a 301 redirection to the main domains (linkbucks.com and eafyfsuh.net)

It would be great if we can use generic service to solve the redirection and then use the linkbucks.com service to get the link.

Any suggestion how to get this @matteocontrini ?

**Comment by matteocontrini** [comment]
`findService` could be called again after following the link, at [this](https://github.com/matteocontrini/node-bypasser/blob/241d6cd2525c1670fd15ee7f94a106655479dc17/index.js#L83) line. If the newly found service is different from the old one, run again.

**Comment by thangngoc89** [comment]
There is no data return at that line. How can I check for it ?

**Comment by matteocontrini** [comment]
Replace `callback` with an anonymous function and inside it call the callback after the appropriate checks.
Tell me if you don't understand and I can try that.

**Comment by thangngoc89** [comment]
Yeah. Could you help me at that? I came from PHP world.

**Comment by matteocontrini** [comment]
b2024067860e9d7cc7c76ae1a676e83db51e9bb0

Build is failing because of services' server issues... Limited concurrent jobs to 1 on Travis.
