### ISSUE TITLE
Link4ad, does it still work?

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/node-bypasser#29]
http://link4ad.net/ seems not to work anymore. When I open a link page I get redirected to the homepage, apparently.
@thangngoc89 do you understand the language of that website? Can you find out what's going on? Thanks

**Comment by thangngoc89** [comment]
Yeah. Looks like that website is down. I got redirected to the homepage too. 

I understand the language of that website. They deleted my account. And I can't create a new account so I think it's better that we remove the service (or just commented it)

**Comment by matteocontrini** [comment]
@thangngoc89 thanks!
