### ISSUE TITLE
Build failing (bc.vc service)

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/node-bypasser#30]
The Travis CI build has been failing today even after various fixes because it seems there's a problem with the bc.vc service.
But I'm able to run all the tests successfully on my local machine.
This needs some investigation.

**Comment by derhuerst** [comment]
> But I'm able to run all the tests successfully on my local machine.

Me too (`master`).

**Comment by andresin87** [comment]
I think it's solved in:
#34

**Comment by matteocontrini** [comment]
And we finally have a passing build, thank you!
