### ISSUE TITLE
Adf.ly broken

### ISSUE THREAD

**Issue by MegamiSyn** [matteocontrini/node-bypasser#38]
http://adf.ly/1DX0XD
1º = Decrypted: 3ace91a5644ca7h|tps://github.com/matteocontrini/node-b{passer/7c1fe1be82ea5799
2º = Decrypted: 1d31a6ffbfa457h|tps://github.com/matteocontrini/node-b{passer/5:5f7290498c8a90
3º = Decrypted: ba6:cbb43ab12ah|tps://github.com/matteocontrini/node-b{passer/&c4b19f8de545315

**Comment by matteocontrini** [comment]
Hi, I'm sorry but I currently don't have time for fixing this. Although the new algorithm for decoding the link has been already extracted in [other](https://github.com/adsbypasser/adsbypasser/commit/5201afe57cc3c0ced523f5776080c8fcd07ea416#diff-cb0f849401ff9e25a08c0542ee7202fa) open source projects.
